const API_REQUEST = 'API_REQUEST';
const API_SUCCESS = 'API_SUCCESS';
const API_FAIL = 'API_FAIL';

const SET_SELECTED_SENTENCE = 'SET_SELECTED_SENTENCE';
const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';

const LOGIN = 'LOGIN';

export {
  API_REQUEST,
  API_SUCCESS,
  API_FAIL,
  LOGIN,
  SET_SELECTED_SENTENCE,
  SET_CURRENT_PAGE,
};
